### ISSUE TITLE
Support for dotnet 6.0 of the DocuEye.CLI

### ISSUE THREAD

**Issue by hideintheclouds** [jacekzwpl/docueye#45]
Tried to install the cli via dotnet tool install, as specified in the readme:
dotnet tool install --global DocuEye.CLI

The problem is my computer is currently setup with dotnet 6.0, while the tool has been created with 8.0

Is there any way net6.0 can also be supported?

Alternatively, it would be useful for the dependencies to be specified somewhere (readme?)

**Comment by jacekzwpl** [comment]
Hi, 
.net 6 will shortly reach end of support date so there is no posibility to fullfil your request. 

Shurely i can extend documentation with information about deps.
