### ISSUE TITLE
Update readme.md to include documentation/example with importing OpenApi

### ISSUE THREAD

**Issue by hideintheclouds** [jacekzwpl/docueye#46]
Currently there is no documentation/concrete example of importing an OpenApi spec and assign it to an element.

Sure, there is some documentation at:  https://github.com/jacekzwpl/docueye/blob/main/Documentation/docs/0006-docueye-cli.md

But maybe some extra information on how to obtain the elementId, and how to set the rest of the parameters.

Also, the OpenApi spec file (--openApiFile param) should be relative to the mapped volume.

After getting the elementId, something similar to:

`docker run -it --rm --network="host" -v "$($PWD):/app/import" jacekzwpl/docueye-cli --import=openapi --docueyeAddress=http://localhost:8080 --adminToken=docueyedmintoken --workspaceId=638d0822-12c7-4998-8647-9c7af7ad2989 --elementId=<ID of the element to associate the OpenApi spec> --openApiFile=./import/openapi.json`

**Comment by jacekzwpl** [comment]
Hi,
There is an example powershell script. You can find it [here](https://github.com/jacekzwpl/docueye/blob/main/ExampleWorkspace/import-openapi.ps1) in the ExampleWorkspace directory.

Let me know if this is enough or You expect something more?
