### ISSUE TITLE
Better documentation & handling of the importKey

### ISSUE THREAD

**Issue by hideintheclouds** [jacekzwpl/docueye#50]
If understood correctly, the import key's type should be GUID.
It seems that the application allows any type of string there, so we can end up with something like this:

![image](https://github.com/user-attachments/assets/e844146c-074a-4ebf-bba9-9f3f31722aa0)

**Comment by jacekzwpl** [comment]
Hi, 
Import key not necessary have to be guid. The idea is that it should be unique string for workspace witch connects changes and prevents from running multiple imports at the same time. 
It can be for example commit hash that points to source version from witch workspace was imported. Personaly I use workflow run identifier. 
I will try to extend documentation with more information about it.
